### ISSUE TITLE
Smart shunt appears for a sec and disappears from Venus os, every 5 to 10 sec! 

### ISSUE THREAD

**Issue by itgenmar** [kscholty/SmartShuntINA226#3]
I have this issue with the shunt appearing for 1 sec and disappearing for 10 sec. 

https://github.com/kscholty/SmartShuntINA226/assets/31439546/b3f890b6-dac6-4a6c-a025-d1614553fdf7

Tried with different serial device and s2 mini. 

Any help?

**Comment by kscholty** [comment]
The reason is probably a loss of connection. This can be caused by different things

1) The shunt crashes.
     Do you have a stable connection to the shunt via WLAN? If it's unstable, please check the power supply. This is often a reason 
     for random behaviour.
2) The communictalion line is instable. 
3) The serial starter is confused.

If you have other devices connected via USB please disconnect them and reboot the GX  device, just to be sure.
If you have access to the console, please post the result of

ls /service

and the file

`/data/log/vedirect.ttyUSBX/current`
where "X" should be the USB device number (1, 2, 3 ...) the smart shunt is connected to.
This migt help.
You can also try a 

`tail -f /data/log/vedirect.ttyUSBX/current`

To watch what's happening.

To check what the serial starter is doing, please check the file

`/data/log/serial-starter/current`

Hard to diagnose from remote
